apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:latest
          env:
            - name: url
              value: "https://zab.star-expertise.local"  # Use HTTPS for the domain
            - name: database__client
              value: "mysql"  # Use MySQL or SQLite (for example)
            - name: database__connection__host
              value: "mysql-db-service"  # MySQL service name
            - name: database__connection__user
              value: "ghost_user"  # MySQL user
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-db-secrets
                  key: mysql-password  # Secret containing MySQL password
            - name: database__connection__database
              value: "ghost_db"  # MySQL database name
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-pvc  # Persistent volume claim for Ghost data

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368  # Forwarding to Ghost's port 2368
  type: ClusterIP  # Internal service; Ingress will expose it externally

---
