apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      component: db
  template:
    metadata:
      labels:
        app: zabbix
        component: db
    spec:
      containers:
        - name: zabbix-db
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: zabbix  # Optional: Define a default database
          volumeMounts:
            - name: zabbix-db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: zabbix-db-data
          persistentVolumeClaim:
            claimName: zabbix-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
spec:
  selector:
    app: zabbix
    component: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service for stateful communication

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"  # Specify your storage class if needed
