apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Ensure HTTPS redirection
    nginx.ingress.kubernetes.io/rewrite-target: "/"  # Handle path rewrites if necessary
spec:
  rules:
    - host: zab.star-expertise.local  # The domain for your Ghost blog
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost-service  # The service that exposes Ghost
                port:
                  number: 80  # Port that Ingress should forward to
  tls:
    - hosts:
        - zab.star-expertise.local  # The domain for which TLS should be applied
      secretName: zabix-ingress-cert  # Name of the TLS secret for HTTPS
