apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Force SSL redirection (HTTP to HTTPS)
spec:
  tls:
    - hosts:
        - zab.star-expertise.local  # The hostname to apply TLS to
      secretName: zabix-ingress-cert  # The secret that holds the TLS certificate
  rules:
    - host: zab.star-expertise.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  number: 80
